name: CI

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          dev: false

      - name: Install wheel
        run: uv run --no-sync maturin develop --uv

      - name: Install ruff
        run: uv tool install ruff

      - name: Check
        run: uv run --no-sync ruff check

  tests:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64
          - runner: ubuntu-24.04
            target: aarch64
          - runner: ubuntu-24.04
            target: armv7

          - runner: windows-latest
            target: x64

          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Install wheel
        run: uv run --no-sync maturin develop

      - name: Tests
        run: uv run --no-sync pytest tests
