name: release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64

          - runner: ubuntu-24.04-arm
            target: aarch64

          - runner: windows-latest
            target: x86_64

          - runner: macos-13
            target: x86_64

          - runner: macos-14
            target: aarch64

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install tools
        run: |
          just install-maturin
          just install-python

      - name: Set up venv
        run: just setup

      - name: Build wheel
        run: just release

      - name: Source distribution
        if: matrix.platform.runner == 'ubuntu-24.04' && matrix.platform.target == 'x86_64'
        run: just sdist

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/*"

      - name: Upload wheel
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        run: just upload
